# Generated by Django 5.0.6 on 2024-06-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Введите название товара', max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', null=True, verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Введите название товара', max_length=100, verbose_name='Товар')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', null=True, verbose_name='Описание товара')),
                ('preview_image', models.ImageField(blank=True, help_text='Загрузите изображения', null=True, upload_to='products/image', verbose_name='Изображения для предварительного просмотра')),
                ('price', models.IntegerField(help_text='Введите цену на продукт', verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['product_name', 'price', 'category'],
            },
        ),
    ]
