# Generated by Django 5.0.6 on 2024-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='slug')),
                ('content', models.TextField(verbose_name='содержание')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение для предпросмотра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статьи')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликовано', verbose_name='опубликовано')),
                ('view_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
