# Generated by Django 4.2.13 on 2024-07-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_blog_author_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name', 'price', 'category'], 'permissions': [('set_published_status', 'Публиковать товар'), ('change_description', 'Изменять описание товара'), ('change_category', 'Изменять категорию товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
