# Generated by Django 4.2.13 on 2024-07-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('blog.set_published_status', 'Публиковать статью')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name', 'price', 'category'], 'permissions': [('product.set_published_status', 'Публиковать товар'), ('product.change_description', 'Изменять описание товара'), ('product.change_category', 'Изменять категорию товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
