# Generated by Django 4.2.13 on 2024-07-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_blog_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('blog_set_published_status', 'Публиковать статью')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name', 'price', 'category'], 'permissions': [('product_set_published_status', 'Публиковать товар'), ('product_change_description', 'Изменять описание товара'), ('product_change_category', 'Изменять категорию товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
